config/routes.rb
Scheduler::Application.routes.draw do

  root 'welcome#home'

  resources :users
  resources :sessions

  get   'meetings/new'   => 'meetings#new',      as: 'new_meeting'
  get   'meetings'       => 'meetings#index',    as: 'meetings'
  post  'meetings'       => 'meetings#create'
  # get   'meetings/edit'
  get   'meetings/:id'   => 'meetings#show',     as: 'meeting'
  post  '/schedule'      => 'meetings#reserve',  as: 'claim_slot'

  get   'sign_up'        => 'users#new',         as: 'sign_up'
  get   '/login'         => 'sessions#new',      as: 'login'
  post  '/login'         => 'sessions#create'
  get   '/logout'        => 'sessions#destroy',  as: 'logout'

  get   'execs'          => 'execs#index'
  post  'execs'          => 'execs#create'
  get   'execs/new'      => 'execs#new',         as: 'new_exec'
  # get   'execs/edit'
  get   'execs/:id'      => 'execs#show',        as: 'exec'

end

app/models/exec.rb
class Exec < ActiveRecord::Base
  belongs_to :user
  has_many :meetings

  validates :user_id, presence: true
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  def self.alphabetize_array
    self.alphabetize.map { |exec| [exec[:name], exec[:id]] }
  end

  def self.alphabetize
    self.all.sort_by { |exec| exec.name }
  end

  def scheduled
    meetings.where.not(user_id: nil)
  end

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  validates :exec_id, presence: true
  #alias_method :starts_at, :start
  extend SimpleCalendar
  has_calendar :attribute => :start
  belongs_to :exec
  belongs_to :user

  scope :available, -> { where(user_id: nil) }

  def available?
    user_id == nil
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  has_many :meetings
  has_many :execs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
      reset_session
      redirect_to welcome_path, notice: "User not found. Sign in please!"
  end

  helper_method :current_user

  def check_for_sign_in
    if current_user == nil
      redirect_to sign_in_path
      flash[:notice] = "You need to sign in to do that."
    end
  end
end

app/controllers/execs_controller.rb
class ExecsController < ApplicationController
  def new
    @exec = Exec.new
  end

  def create
    @exec = Exec.new(exec_params)
    if @exec.save
      flash[:notice] = 'Exec was successfully created.'
      redirect_to execs_path
    else
      flash[:notice] = 'There was a problem registering this executive!'
      render :new
    end
  end

  def edit
  end

  def update
  end

  # shows executive's full schedule but only if an admin?
  def show
    @exec = Exec.find(params[:id])
    @meetings = @exec.meetings.available
    @scheduled = @exec.scheduled
  end

  # index should show all available meeting times by executive
  def index
    @execs = Exec.all
  end

  private
  def exec_params
    params.require(:exec).permit(:name, :email, :user_id)
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # this is only for admins to create a slot for an exec. need before filter
  # to check if user is an admin?

  # need before filter to check for logged in user for 'reserve' action

  def new
    @meeting = Meeting.new
    @execs = current_user.execs.alphabetize_array if current_user
  end

  def create
    @meeting = Meeting.new(meeting_params)
    if @meeting.save
      redirect_to meeting_path(@meeting)
      flash[:notice] = "You've created a new meeting!"
    else
      flash[:notice] = "There was a problem saving this meeting."
      render :new
    end
  end

  def edit
  end

  def update
  end

  def index
    @meetings = Meeting.all
    render :partial => 'index'
  end

  def show
  end

  def reserve
    @meeting = Meeting.find(params[:meeting])
    @meeting.user_id = current_user.id
    exec = Exec.find(@meeting.exec_id)
    datetime = @meeting.start.getlocal.strftime("%l:%M %p %a on %d %b %Y")
    if @meeting.save
      flash[:notice] = "You are scheduled to meet with #{exec.name} on #{datetime}"
      redirect_to root_path
    else
      flash[:notice] = "There was a problem claiming this slot. Please try again!"
      render exec_path(exec)
    end
  end

  private

  def set_meeting

    @meeting = Meeting.find(params[:id])
  end

  def meeting_params
    params.require(:meeting).permit(:exec_id, :location, :user_id, :start, :duration)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			flash[:notice] = "You have successfully signed in!"
			redirect_to root_path
		else
			flash[:notice] = "Invalid email/password. Please try again."
			redirect_to root_path
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "You have successfully logged out!"
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # include admin privileges for user index to assign admins
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'User was successfully created.'
      redirect_to root_path
    else
      flash[:notice] = 'There was a problem creating your account!'
      render :new
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:admin, :name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @meetings = Meeting.available
    @execs = Exec.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/execs_helper.rb
module ExecsHelper
end

app/helpers/meeting_helper.rb
module MeetingHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/execs/_form.html.erb
<%= form_for(@exec) do |f| %>
  <div class='errors'>
    <% if @exec.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@exec.errors.count, "error") %> prohibited this executive from being saved:
        </h2>
        <ul>
          <% @exec.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/execs/edit.html.erb
<h1>Execs#edit</h1>
<p>Find me in app/views/execs/edit.html.erb</p>

app/views/execs/index.html.erb
<div class='col-lg-3'></div>
<div class='show col-lg-6'>
  <h1 class='text-center'>Executives</h1><hr>
  <ul>
    <% @execs.each do |exec| %>
    <li><%=link_to exec.name, exec_path(exec) %> |
      <%= exec.email %>
    </li>
    <% end %>
  </ul>
</div>
<div class='col-lg-3'></div>

app/views/execs/new.html.erb
<div class='col-lg-3'></div>
<div class='signup-form col-lg-6'>
  <h1>Register an Executive</h1>
  <%= render 'form' %>
</div>
<div class='col-lg-3'></div>

app/views/execs/show.html.erb
<div class='col-lg-3'></div>
  <div class='show exec-show col-lg-6'>
    <h1><%= @exec.name %> <small><%=@exec.email %></small></h1><hr>
    <% if @exec.user == current_user %>
      <div>
        <h2>Scheduled meetings</h2>
          <table class='exec-schedule'>
          <% @scheduled.each do |meeting| %>
            <tr>
              <td><%= meeting.start.strftime("%l:%M %p %a on %d %b %Y") %></td>
              <td><%= meeting.user.name %></td>
              <td><%= meeting.user.email %></td>
            </tr>
          <% end %>
        </table>
        <div>
          <%= link_to "Add timeslot", new_meeting_path, class: 'btn btn-default' %>
        </div>
      </div><hr>
    <% end %>

    <div>
      <h2>Available Times:</h2>
      <table class='exec-schedule'>
        <% @meetings.each do |meeting| %>
          <tr>
            <td><%= meeting.start.strftime("%l:%M %p %a on %d %b %Y") %></td>
            <td><%= link_to "Claim!", claim_slot_path(meeting: meeting.id), method: 'post', class: 'btn btn-default' %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
<div class='col-lg-3'></div>

app/views/layouts/_banner.html.erb
<div class='navbar'>
  <ul class='nav-main'>
    <div class='nav-div icon'>
      <%= link_to(image_tag("emc-isilon-logo.jpg", :alt => "EMC Isilon logo", size:'100x100', :title => "Click here to return to Home"), "/") %>
    </div>
    <div class='nav-div links'>
      <% if current_user %>
        <li>
          <span class='current-user'>Signed in as <%= link_to "#{current_user.name}", user_path(current_user) %></span>
          <%= link_to "Sign out", "/logout", class: 'btn btn-default' %>
        </li>
      <% else %>
        <li class='login open-modal'><%= link_to "Log In", "/login", class: 'btn btn-default'%></li>
      <% end %>
    </div>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scheduler</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class='background close-modal'></div>
    <%= render "layouts/banner" %>
    <div class='modal-container'>
      <div class='modal-background close-modal'>
      </div>
      <div class='content'>
        <a href="#" class="btn btn-default exit-modal close-modal">Close</a>
        <h1>Log in</h1><hr>
        <%= form_tag sessions_path do %>
          <p>
            <%= label_tag :email %><br />
            <%= text_field_tag :email, params[:email] %>
          </p>
          <p>
            <%= label_tag :password %><br />
            <%= password_field_tag :password %>
          </p>
          <p class="button">
            <%= submit_tag "Log In" %>
          </p>
        <% end %>
        (New user? <%= link_to "Sign up", sign_up_path %>.)
      </div>
    </div>
    <% if flash.notice %>
      <div class="alert alert-warning flash text-center"><%= flash.notice %></div>
    <% end %>
    <%= yield %>

  </body>
</html>

app/views/meetings/_form.html.erb
<div class='form'>
  <%= form_for(@meeting) do |f| %>
    <div class='errors'>
      <% if @meeting.errors.any? %>
      <div class="error_messages">
        <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>
        <ul>
          <% @meeting.errors.full_messages.each do |message| %>
            <li> <%= message %> </li>
          <% end %>
        </ul>
      </div>
      <% end %>
    </div>

    <div class="field">
      <%= f.label :exec_id, "Executive" %><br>
      <%= f.select(:exec_id, @execs) %>
      <p>Executive you want not here? <%= link_to 'Register an Executive', new_exec_path %></p>
    </div>

    <!-- Issue with saving the local time -->
    <div class="field">
      <%= f.label :start %><br>
      <%= f.datetime_local_field :start %>
    </div>

    <div class="field">
      <%= f.label :duration_in_minutes %><br>
      <%= f.number_field :duration %>
    </div>

    <br>
    <div class="field">
      <%= f.label :location %><br>
      <%= f.text_field :location %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/meetings/_index.html.erb
<div class='calendar-container col-md-8'>
  <div class='calendar'>
    <%= month_calendar events: @meetings do |date, meetings| %>
      <%= date.strftime('%d') %>
        <% meetings.each do |meeting| %>
          <div>
            <%= link_to "#{meeting.exec.name + " " + meeting.start.strftime('%I:%M %p')}","#", class: 'timeslot', data: { exec_id: meeting.exec.id } %>
            <div class='claimbox'>
              <%= link_to '[X]', "#", class: 'close-icon' %>
              <h3><%=link_to meeting.exec.name, exec_path(meeting.exec.id) %></h3>
              <ul>
                <li>Date: <%= meeting.start.strftime("%A, %B %e") %></li>
                <li>Time: <%= meeting.start.strftime("%l:%M %P") + " - " + (meeting.start + 30.minutes).strftime("%l:%M %P")%></li>
              </ul>
              <% if current_user %>
                <%= link_to "Claim!", claim_slot_path(meeting: meeting.id), method: 'post', class: 'btn btn-default btn-block' %>
              <% end %>
            </div>
          </div>
       <% end %>
    <% end %>
  </div>
</div>

app/views/meetings/edit.html.erb
<h1>Meetings#edit</h1>
<p>Find me in app/views/meetings/edit.html.erb</p>

app/views/meetings/new.html.erb
<div class='col-lg-3'></div>
  <div class='signup-form col-lg-6'>
    <h1>Schedule Meeting</h1>

    <% if current_user && current_user.admin && current_user.execs.count > 0 %>
      <%= render 'form' %>

    <% else %>
      You must be logged in to schedule a meeting!
    <% end %>
  <br>
  <br>

  </div>
<div class='col-lg-3'></div>

app/views/meetings/show.html.erb
<div class='col-lg-3'></div>
  <div class='show col-lg-6'>
  <h1>Meeting with <%=link_to @meeting.exec.name, exec_path(@meeting.exec.id) %></h1>
    Date: <%= @meeting.start.strftime("%A, %B %e") %><br>
    Time: <%= @meeting.start.strftime("%l:%M %P") + " - " + (@meeting.start + 30.minutes).strftime("%l:%M %P")%><br>
    Available? <%= @meeting.user_id == nil %>
  </div>
<div class='col-lg-3'></div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Admin</th>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.admin %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class='col-lg-3'></div>
  <div class='signup-form col-lg-6'>
    <h1>New user</h1>
    <%= render 'form' %>
  </div>
<div class='col-lg-3'></div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Meetings:</strong>
  <%= @user.meetings.inspect %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/home.html.erb
<div class='container-fluid'>
  <div class='row'>
    <div class='col-md-3'>
    	<div class='sidebar'>
        <h2><%=link_to "All Executives", root_path %></h2>
        <ul>
          <% @execs.each do |exec| %>
            <li><%=link_to exec.name, "#", class: 'exec',  data: { exec_id: exec.id } %></li>
          <% end %>
        </ul>
			  	<%#= link_to "Executives Index", execs_path, class: 'btn btn-default' %>
    			<!-- only show this if admin -->
          <% if current_user %>
            <% if current_user.admin %>
              <%= link_to "Schedule Meeting", new_meeting_path, class: 'btn btn-default' %>
            <% end %>
          <% end %>
			</div>
    </div>

		<%= render 'meetings/index' %>

    <div class='col-md-1'></div>
  </div>
</div>